# Generated by Django 5.2.4 on 2025-10-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
